//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBSupportCenter.WSsupport1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSsupportCenterClassSoap", Namespace="http://tempuri.org/")]
    public partial class WSsupportCenterClass : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WSOptenerArtOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSOptenerCatgOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSBusquedaTituloOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSConsultarArticuloxIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSBusquedaArticulosxClickOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGuardarPalabraBuscadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSOpregistrarArtOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSOpconsultarArtxValidarOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSConsultarArtEdicionOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSConsultarCategoriasOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSEditarArtOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSConsultarArtPorValidarOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSOguardarEstatusArticuloAprobarOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSConsultarGruposxUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSconsultarCategoriasOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSgetSinHijosOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSgetSinPadresOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSgetSizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSgetListOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSguardarCategoriasOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSguardarCategoriasEditOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSguardarRelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSeliminarCategoriasOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSObtenerArticuloOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSsupportCenterClass() {
            this.Url = global::WBSupportCenter.Properties.Settings.Default.WBSupportCenter_WSsupport1_WSsupportCenterClass;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WSOptenerArtCompletedEventHandler WSOptenerArtCompleted;
        
        /// <remarks/>
        public event WSOptenerCatgCompletedEventHandler WSOptenerCatgCompleted;
        
        /// <remarks/>
        public event WSBusquedaTituloCompletedEventHandler WSBusquedaTituloCompleted;
        
        /// <remarks/>
        public event WSConsultarArticuloxIdCompletedEventHandler WSConsultarArticuloxIdCompleted;
        
        /// <remarks/>
        public event WSBusquedaArticulosxClickCompletedEventHandler WSBusquedaArticulosxClickCompleted;
        
        /// <remarks/>
        public event WSGuardarPalabraBuscadaCompletedEventHandler WSGuardarPalabraBuscadaCompleted;
        
        /// <remarks/>
        public event WSOpregistrarArtCompletedEventHandler WSOpregistrarArtCompleted;
        
        /// <remarks/>
        public event WSOpconsultarArtxValidarCompletedEventHandler WSOpconsultarArtxValidarCompleted;
        
        /// <remarks/>
        public event WSConsultarArtEdicionCompletedEventHandler WSConsultarArtEdicionCompleted;
        
        /// <remarks/>
        public event WSConsultarCategoriasCompletedEventHandler WSConsultarCategoriasCompleted;
        
        /// <remarks/>
        public event WSEditarArtCompletedEventHandler WSEditarArtCompleted;
        
        /// <remarks/>
        public event WSConsultarArtPorValidarCompletedEventHandler WSConsultarArtPorValidarCompleted;
        
        /// <remarks/>
        public event WSOguardarEstatusArticuloAprobarCompletedEventHandler WSOguardarEstatusArticuloAprobarCompleted;
        
        /// <remarks/>
        public event WSConsultarGruposxUsuarioCompletedEventHandler WSConsultarGruposxUsuarioCompleted;
        
        /// <remarks/>
        public event WSconsultarCategoriasCompletedEventHandler WSconsultarCategoriasCompleted;
        
        /// <remarks/>
        public event WSgetSinHijosCompletedEventHandler WSgetSinHijosCompleted;
        
        /// <remarks/>
        public event WSgetSinPadresCompletedEventHandler WSgetSinPadresCompleted;
        
        /// <remarks/>
        public event WSgetSizeCompletedEventHandler WSgetSizeCompleted;
        
        /// <remarks/>
        public event WSgetListCompletedEventHandler WSgetListCompleted;
        
        /// <remarks/>
        public event WSguardarCategoriasCompletedEventHandler WSguardarCategoriasCompleted;
        
        /// <remarks/>
        public event WSguardarCategoriasEditCompletedEventHandler WSguardarCategoriasEditCompleted;
        
        /// <remarks/>
        public event WSguardarRelacionCompletedEventHandler WSguardarRelacionCompleted;
        
        /// <remarks/>
        public event WSeliminarCategoriasCompletedEventHandler WSeliminarCategoriasCompleted;
        
        /// <remarks/>
        public event WSObtenerArticuloCompletedEventHandler WSObtenerArticuloCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSOptenerArt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Articulos[] WSOptenerArt() {
            object[] results = this.Invoke("WSOptenerArt", new object[0]);
            return ((Articulos[])(results[0]));
        }
        
        /// <remarks/>
        public void WSOptenerArtAsync() {
            this.WSOptenerArtAsync(null);
        }
        
        /// <remarks/>
        public void WSOptenerArtAsync(object userState) {
            if ((this.WSOptenerArtOperationCompleted == null)) {
                this.WSOptenerArtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSOptenerArtOperationCompleted);
            }
            this.InvokeAsync("WSOptenerArt", new object[0], this.WSOptenerArtOperationCompleted, userState);
        }
        
        private void OnWSOptenerArtOperationCompleted(object arg) {
            if ((this.WSOptenerArtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSOptenerArtCompleted(this, new WSOptenerArtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSOptenerCatg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoriasxSubcategorias[] WSOptenerCatg() {
            object[] results = this.Invoke("WSOptenerCatg", new object[0]);
            return ((CategoriasxSubcategorias[])(results[0]));
        }
        
        /// <remarks/>
        public void WSOptenerCatgAsync() {
            this.WSOptenerCatgAsync(null);
        }
        
        /// <remarks/>
        public void WSOptenerCatgAsync(object userState) {
            if ((this.WSOptenerCatgOperationCompleted == null)) {
                this.WSOptenerCatgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSOptenerCatgOperationCompleted);
            }
            this.InvokeAsync("WSOptenerCatg", new object[0], this.WSOptenerCatgOperationCompleted, userState);
        }
        
        private void OnWSOptenerCatgOperationCompleted(object arg) {
            if ((this.WSOptenerCatgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSOptenerCatgCompleted(this, new WSOptenerCatgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSBusquedaTitulo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BusquedaTitulo[] WSBusquedaTitulo(string palabra) {
            object[] results = this.Invoke("WSBusquedaTitulo", new object[] {
                        palabra});
            return ((BusquedaTitulo[])(results[0]));
        }
        
        /// <remarks/>
        public void WSBusquedaTituloAsync(string palabra) {
            this.WSBusquedaTituloAsync(palabra, null);
        }
        
        /// <remarks/>
        public void WSBusquedaTituloAsync(string palabra, object userState) {
            if ((this.WSBusquedaTituloOperationCompleted == null)) {
                this.WSBusquedaTituloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSBusquedaTituloOperationCompleted);
            }
            this.InvokeAsync("WSBusquedaTitulo", new object[] {
                        palabra}, this.WSBusquedaTituloOperationCompleted, userState);
        }
        
        private void OnWSBusquedaTituloOperationCompleted(object arg) {
            if ((this.WSBusquedaTituloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSBusquedaTituloCompleted(this, new WSBusquedaTituloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSConsultarArticuloxId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Articulos[] WSConsultarArticuloxId(int idArt) {
            object[] results = this.Invoke("WSConsultarArticuloxId", new object[] {
                        idArt});
            return ((Articulos[])(results[0]));
        }
        
        /// <remarks/>
        public void WSConsultarArticuloxIdAsync(int idArt) {
            this.WSConsultarArticuloxIdAsync(idArt, null);
        }
        
        /// <remarks/>
        public void WSConsultarArticuloxIdAsync(int idArt, object userState) {
            if ((this.WSConsultarArticuloxIdOperationCompleted == null)) {
                this.WSConsultarArticuloxIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSConsultarArticuloxIdOperationCompleted);
            }
            this.InvokeAsync("WSConsultarArticuloxId", new object[] {
                        idArt}, this.WSConsultarArticuloxIdOperationCompleted, userState);
        }
        
        private void OnWSConsultarArticuloxIdOperationCompleted(object arg) {
            if ((this.WSConsultarArticuloxIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSConsultarArticuloxIdCompleted(this, new WSConsultarArticuloxIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSBusquedaArticulosxClick", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Articulos[] WSBusquedaArticulosxClick(string palabra) {
            object[] results = this.Invoke("WSBusquedaArticulosxClick", new object[] {
                        palabra});
            return ((Articulos[])(results[0]));
        }
        
        /// <remarks/>
        public void WSBusquedaArticulosxClickAsync(string palabra) {
            this.WSBusquedaArticulosxClickAsync(palabra, null);
        }
        
        /// <remarks/>
        public void WSBusquedaArticulosxClickAsync(string palabra, object userState) {
            if ((this.WSBusquedaArticulosxClickOperationCompleted == null)) {
                this.WSBusquedaArticulosxClickOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSBusquedaArticulosxClickOperationCompleted);
            }
            this.InvokeAsync("WSBusquedaArticulosxClick", new object[] {
                        palabra}, this.WSBusquedaArticulosxClickOperationCompleted, userState);
        }
        
        private void OnWSBusquedaArticulosxClickOperationCompleted(object arg) {
            if ((this.WSBusquedaArticulosxClickCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSBusquedaArticulosxClickCompleted(this, new WSBusquedaArticulosxClickCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGuardarPalabraBuscada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int WSGuardarPalabraBuscada(string palabra) {
            object[] results = this.Invoke("WSGuardarPalabraBuscada", new object[] {
                        palabra});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void WSGuardarPalabraBuscadaAsync(string palabra) {
            this.WSGuardarPalabraBuscadaAsync(palabra, null);
        }
        
        /// <remarks/>
        public void WSGuardarPalabraBuscadaAsync(string palabra, object userState) {
            if ((this.WSGuardarPalabraBuscadaOperationCompleted == null)) {
                this.WSGuardarPalabraBuscadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGuardarPalabraBuscadaOperationCompleted);
            }
            this.InvokeAsync("WSGuardarPalabraBuscada", new object[] {
                        palabra}, this.WSGuardarPalabraBuscadaOperationCompleted, userState);
        }
        
        private void OnWSGuardarPalabraBuscadaOperationCompleted(object arg) {
            if ((this.WSGuardarPalabraBuscadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGuardarPalabraBuscadaCompleted(this, new WSGuardarPalabraBuscadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSOpregistrarArt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int WSOpregistrarArt(string nombreArticulo, string contenido, string categorias, string tags, string grupos) {
            object[] results = this.Invoke("WSOpregistrarArt", new object[] {
                        nombreArticulo,
                        contenido,
                        categorias,
                        tags,
                        grupos});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void WSOpregistrarArtAsync(string nombreArticulo, string contenido, string categorias, string tags, string grupos) {
            this.WSOpregistrarArtAsync(nombreArticulo, contenido, categorias, tags, grupos, null);
        }
        
        /// <remarks/>
        public void WSOpregistrarArtAsync(string nombreArticulo, string contenido, string categorias, string tags, string grupos, object userState) {
            if ((this.WSOpregistrarArtOperationCompleted == null)) {
                this.WSOpregistrarArtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSOpregistrarArtOperationCompleted);
            }
            this.InvokeAsync("WSOpregistrarArt", new object[] {
                        nombreArticulo,
                        contenido,
                        categorias,
                        tags,
                        grupos}, this.WSOpregistrarArtOperationCompleted, userState);
        }
        
        private void OnWSOpregistrarArtOperationCompleted(object arg) {
            if ((this.WSOpregistrarArtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSOpregistrarArtCompleted(this, new WSOpregistrarArtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSOpconsultarArtxValidar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WSOpconsultarArtxValidar() {
            object[] results = this.Invoke("WSOpconsultarArtxValidar", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WSOpconsultarArtxValidarAsync() {
            this.WSOpconsultarArtxValidarAsync(null);
        }
        
        /// <remarks/>
        public void WSOpconsultarArtxValidarAsync(object userState) {
            if ((this.WSOpconsultarArtxValidarOperationCompleted == null)) {
                this.WSOpconsultarArtxValidarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSOpconsultarArtxValidarOperationCompleted);
            }
            this.InvokeAsync("WSOpconsultarArtxValidar", new object[0], this.WSOpconsultarArtxValidarOperationCompleted, userState);
        }
        
        private void OnWSOpconsultarArtxValidarOperationCompleted(object arg) {
            if ((this.WSOpconsultarArtxValidarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSOpconsultarArtxValidarCompleted(this, new WSOpconsultarArtxValidarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSConsultarArtEdicion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WSConsultarArtEdicion(int idArt) {
            object[] results = this.Invoke("WSConsultarArtEdicion", new object[] {
                        idArt});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WSConsultarArtEdicionAsync(int idArt) {
            this.WSConsultarArtEdicionAsync(idArt, null);
        }
        
        /// <remarks/>
        public void WSConsultarArtEdicionAsync(int idArt, object userState) {
            if ((this.WSConsultarArtEdicionOperationCompleted == null)) {
                this.WSConsultarArtEdicionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSConsultarArtEdicionOperationCompleted);
            }
            this.InvokeAsync("WSConsultarArtEdicion", new object[] {
                        idArt}, this.WSConsultarArtEdicionOperationCompleted, userState);
        }
        
        private void OnWSConsultarArtEdicionOperationCompleted(object arg) {
            if ((this.WSConsultarArtEdicionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSConsultarArtEdicionCompleted(this, new WSConsultarArtEdicionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSConsultarCategorias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WSConsultarCategorias(int idPadreCat) {
            object[] results = this.Invoke("WSConsultarCategorias", new object[] {
                        idPadreCat});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WSConsultarCategoriasAsync(int idPadreCat) {
            this.WSConsultarCategoriasAsync(idPadreCat, null);
        }
        
        /// <remarks/>
        public void WSConsultarCategoriasAsync(int idPadreCat, object userState) {
            if ((this.WSConsultarCategoriasOperationCompleted == null)) {
                this.WSConsultarCategoriasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSConsultarCategoriasOperationCompleted);
            }
            this.InvokeAsync("WSConsultarCategorias", new object[] {
                        idPadreCat}, this.WSConsultarCategoriasOperationCompleted, userState);
        }
        
        private void OnWSConsultarCategoriasOperationCompleted(object arg) {
            if ((this.WSConsultarCategoriasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSConsultarCategoriasCompleted(this, new WSConsultarCategoriasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSEditarArt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int WSEditarArt(int idArticulo, string nombreArticulo, string contenido, string categorias, string tags) {
            object[] results = this.Invoke("WSEditarArt", new object[] {
                        idArticulo,
                        nombreArticulo,
                        contenido,
                        categorias,
                        tags});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void WSEditarArtAsync(int idArticulo, string nombreArticulo, string contenido, string categorias, string tags) {
            this.WSEditarArtAsync(idArticulo, nombreArticulo, contenido, categorias, tags, null);
        }
        
        /// <remarks/>
        public void WSEditarArtAsync(int idArticulo, string nombreArticulo, string contenido, string categorias, string tags, object userState) {
            if ((this.WSEditarArtOperationCompleted == null)) {
                this.WSEditarArtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSEditarArtOperationCompleted);
            }
            this.InvokeAsync("WSEditarArt", new object[] {
                        idArticulo,
                        nombreArticulo,
                        contenido,
                        categorias,
                        tags}, this.WSEditarArtOperationCompleted, userState);
        }
        
        private void OnWSEditarArtOperationCompleted(object arg) {
            if ((this.WSEditarArtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSEditarArtCompleted(this, new WSEditarArtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSConsultarArtPorValidar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WSConsultarArtPorValidar() {
            object[] results = this.Invoke("WSConsultarArtPorValidar", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WSConsultarArtPorValidarAsync() {
            this.WSConsultarArtPorValidarAsync(null);
        }
        
        /// <remarks/>
        public void WSConsultarArtPorValidarAsync(object userState) {
            if ((this.WSConsultarArtPorValidarOperationCompleted == null)) {
                this.WSConsultarArtPorValidarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSConsultarArtPorValidarOperationCompleted);
            }
            this.InvokeAsync("WSConsultarArtPorValidar", new object[0], this.WSConsultarArtPorValidarOperationCompleted, userState);
        }
        
        private void OnWSConsultarArtPorValidarOperationCompleted(object arg) {
            if ((this.WSConsultarArtPorValidarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSConsultarArtPorValidarCompleted(this, new WSConsultarArtPorValidarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSOguardarEstatusArticuloAprobar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSOguardarEstatusArticuloAprobar(int idArticulo, int estatus, string comentario) {
            object[] results = this.Invoke("WSOguardarEstatusArticuloAprobar", new object[] {
                        idArticulo,
                        estatus,
                        comentario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSOguardarEstatusArticuloAprobarAsync(int idArticulo, int estatus, string comentario) {
            this.WSOguardarEstatusArticuloAprobarAsync(idArticulo, estatus, comentario, null);
        }
        
        /// <remarks/>
        public void WSOguardarEstatusArticuloAprobarAsync(int idArticulo, int estatus, string comentario, object userState) {
            if ((this.WSOguardarEstatusArticuloAprobarOperationCompleted == null)) {
                this.WSOguardarEstatusArticuloAprobarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSOguardarEstatusArticuloAprobarOperationCompleted);
            }
            this.InvokeAsync("WSOguardarEstatusArticuloAprobar", new object[] {
                        idArticulo,
                        estatus,
                        comentario}, this.WSOguardarEstatusArticuloAprobarOperationCompleted, userState);
        }
        
        private void OnWSOguardarEstatusArticuloAprobarOperationCompleted(object arg) {
            if ((this.WSOguardarEstatusArticuloAprobarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSOguardarEstatusArticuloAprobarCompleted(this, new WSOguardarEstatusArticuloAprobarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSConsultarGruposxUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WSConsultarGruposxUsuario(int idUsuario) {
            object[] results = this.Invoke("WSConsultarGruposxUsuario", new object[] {
                        idUsuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WSConsultarGruposxUsuarioAsync(int idUsuario) {
            this.WSConsultarGruposxUsuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void WSConsultarGruposxUsuarioAsync(int idUsuario, object userState) {
            if ((this.WSConsultarGruposxUsuarioOperationCompleted == null)) {
                this.WSConsultarGruposxUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSConsultarGruposxUsuarioOperationCompleted);
            }
            this.InvokeAsync("WSConsultarGruposxUsuario", new object[] {
                        idUsuario}, this.WSConsultarGruposxUsuarioOperationCompleted, userState);
        }
        
        private void OnWSConsultarGruposxUsuarioOperationCompleted(object arg) {
            if ((this.WSConsultarGruposxUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSConsultarGruposxUsuarioCompleted(this, new WSConsultarGruposxUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSconsultarCategorias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoriasxSubcategorias[] WSconsultarCategorias() {
            object[] results = this.Invoke("WSconsultarCategorias", new object[0]);
            return ((CategoriasxSubcategorias[])(results[0]));
        }
        
        /// <remarks/>
        public void WSconsultarCategoriasAsync() {
            this.WSconsultarCategoriasAsync(null);
        }
        
        /// <remarks/>
        public void WSconsultarCategoriasAsync(object userState) {
            if ((this.WSconsultarCategoriasOperationCompleted == null)) {
                this.WSconsultarCategoriasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSconsultarCategoriasOperationCompleted);
            }
            this.InvokeAsync("WSconsultarCategorias", new object[0], this.WSconsultarCategoriasOperationCompleted, userState);
        }
        
        private void OnWSconsultarCategoriasOperationCompleted(object arg) {
            if ((this.WSconsultarCategoriasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSconsultarCategoriasCompleted(this, new WSconsultarCategoriasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSgetSinHijos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoriasxSubcategorias[] WSgetSinHijos() {
            object[] results = this.Invoke("WSgetSinHijos", new object[0]);
            return ((CategoriasxSubcategorias[])(results[0]));
        }
        
        /// <remarks/>
        public void WSgetSinHijosAsync() {
            this.WSgetSinHijosAsync(null);
        }
        
        /// <remarks/>
        public void WSgetSinHijosAsync(object userState) {
            if ((this.WSgetSinHijosOperationCompleted == null)) {
                this.WSgetSinHijosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSgetSinHijosOperationCompleted);
            }
            this.InvokeAsync("WSgetSinHijos", new object[0], this.WSgetSinHijosOperationCompleted, userState);
        }
        
        private void OnWSgetSinHijosOperationCompleted(object arg) {
            if ((this.WSgetSinHijosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSgetSinHijosCompleted(this, new WSgetSinHijosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSgetSinPadres", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoriasxSubcategorias[] WSgetSinPadres(int idPadre) {
            object[] results = this.Invoke("WSgetSinPadres", new object[] {
                        idPadre});
            return ((CategoriasxSubcategorias[])(results[0]));
        }
        
        /// <remarks/>
        public void WSgetSinPadresAsync(int idPadre) {
            this.WSgetSinPadresAsync(idPadre, null);
        }
        
        /// <remarks/>
        public void WSgetSinPadresAsync(int idPadre, object userState) {
            if ((this.WSgetSinPadresOperationCompleted == null)) {
                this.WSgetSinPadresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSgetSinPadresOperationCompleted);
            }
            this.InvokeAsync("WSgetSinPadres", new object[] {
                        idPadre}, this.WSgetSinPadresOperationCompleted, userState);
        }
        
        private void OnWSgetSinPadresOperationCompleted(object arg) {
            if ((this.WSgetSinPadresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSgetSinPadresCompleted(this, new WSgetSinPadresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSgetSize", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoriasxSubcategorias[] WSgetSize(int idCategoria) {
            object[] results = this.Invoke("WSgetSize", new object[] {
                        idCategoria});
            return ((CategoriasxSubcategorias[])(results[0]));
        }
        
        /// <remarks/>
        public void WSgetSizeAsync(int idCategoria) {
            this.WSgetSizeAsync(idCategoria, null);
        }
        
        /// <remarks/>
        public void WSgetSizeAsync(int idCategoria, object userState) {
            if ((this.WSgetSizeOperationCompleted == null)) {
                this.WSgetSizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSgetSizeOperationCompleted);
            }
            this.InvokeAsync("WSgetSize", new object[] {
                        idCategoria}, this.WSgetSizeOperationCompleted, userState);
        }
        
        private void OnWSgetSizeOperationCompleted(object arg) {
            if ((this.WSgetSizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSgetSizeCompleted(this, new WSgetSizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSgetList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoriasxSubcategorias[] WSgetList(int idCategoria) {
            object[] results = this.Invoke("WSgetList", new object[] {
                        idCategoria});
            return ((CategoriasxSubcategorias[])(results[0]));
        }
        
        /// <remarks/>
        public void WSgetListAsync(int idCategoria) {
            this.WSgetListAsync(idCategoria, null);
        }
        
        /// <remarks/>
        public void WSgetListAsync(int idCategoria, object userState) {
            if ((this.WSgetListOperationCompleted == null)) {
                this.WSgetListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSgetListOperationCompleted);
            }
            this.InvokeAsync("WSgetList", new object[] {
                        idCategoria}, this.WSgetListOperationCompleted, userState);
        }
        
        private void OnWSgetListOperationCompleted(object arg) {
            if ((this.WSgetListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSgetListCompleted(this, new WSgetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSguardarCategorias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSguardarCategorias(string nombreCategoria, string descripcion) {
            object[] results = this.Invoke("WSguardarCategorias", new object[] {
                        nombreCategoria,
                        descripcion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSguardarCategoriasAsync(string nombreCategoria, string descripcion) {
            this.WSguardarCategoriasAsync(nombreCategoria, descripcion, null);
        }
        
        /// <remarks/>
        public void WSguardarCategoriasAsync(string nombreCategoria, string descripcion, object userState) {
            if ((this.WSguardarCategoriasOperationCompleted == null)) {
                this.WSguardarCategoriasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSguardarCategoriasOperationCompleted);
            }
            this.InvokeAsync("WSguardarCategorias", new object[] {
                        nombreCategoria,
                        descripcion}, this.WSguardarCategoriasOperationCompleted, userState);
        }
        
        private void OnWSguardarCategoriasOperationCompleted(object arg) {
            if ((this.WSguardarCategoriasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSguardarCategoriasCompleted(this, new WSguardarCategoriasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSguardarCategoriasEdit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSguardarCategoriasEdit(string nombreCategoria, string descripcion, int idCategoria) {
            object[] results = this.Invoke("WSguardarCategoriasEdit", new object[] {
                        nombreCategoria,
                        descripcion,
                        idCategoria});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSguardarCategoriasEditAsync(string nombreCategoria, string descripcion, int idCategoria) {
            this.WSguardarCategoriasEditAsync(nombreCategoria, descripcion, idCategoria, null);
        }
        
        /// <remarks/>
        public void WSguardarCategoriasEditAsync(string nombreCategoria, string descripcion, int idCategoria, object userState) {
            if ((this.WSguardarCategoriasEditOperationCompleted == null)) {
                this.WSguardarCategoriasEditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSguardarCategoriasEditOperationCompleted);
            }
            this.InvokeAsync("WSguardarCategoriasEdit", new object[] {
                        nombreCategoria,
                        descripcion,
                        idCategoria}, this.WSguardarCategoriasEditOperationCompleted, userState);
        }
        
        private void OnWSguardarCategoriasEditOperationCompleted(object arg) {
            if ((this.WSguardarCategoriasEditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSguardarCategoriasEditCompleted(this, new WSguardarCategoriasEditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSguardarRelacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSguardarRelacion(string nombreCategoria, int idCategoria) {
            object[] results = this.Invoke("WSguardarRelacion", new object[] {
                        nombreCategoria,
                        idCategoria});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSguardarRelacionAsync(string nombreCategoria, int idCategoria) {
            this.WSguardarRelacionAsync(nombreCategoria, idCategoria, null);
        }
        
        /// <remarks/>
        public void WSguardarRelacionAsync(string nombreCategoria, int idCategoria, object userState) {
            if ((this.WSguardarRelacionOperationCompleted == null)) {
                this.WSguardarRelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSguardarRelacionOperationCompleted);
            }
            this.InvokeAsync("WSguardarRelacion", new object[] {
                        nombreCategoria,
                        idCategoria}, this.WSguardarRelacionOperationCompleted, userState);
        }
        
        private void OnWSguardarRelacionOperationCompleted(object arg) {
            if ((this.WSguardarRelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSguardarRelacionCompleted(this, new WSguardarRelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSeliminarCategorias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSeliminarCategorias(int idCategoria) {
            object[] results = this.Invoke("WSeliminarCategorias", new object[] {
                        idCategoria});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSeliminarCategoriasAsync(int idCategoria) {
            this.WSeliminarCategoriasAsync(idCategoria, null);
        }
        
        /// <remarks/>
        public void WSeliminarCategoriasAsync(int idCategoria, object userState) {
            if ((this.WSeliminarCategoriasOperationCompleted == null)) {
                this.WSeliminarCategoriasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSeliminarCategoriasOperationCompleted);
            }
            this.InvokeAsync("WSeliminarCategorias", new object[] {
                        idCategoria}, this.WSeliminarCategoriasOperationCompleted, userState);
        }
        
        private void OnWSeliminarCategoriasOperationCompleted(object arg) {
            if ((this.WSeliminarCategoriasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSeliminarCategoriasCompleted(this, new WSeliminarCategoriasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSObtenerArticulo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Reporte[] WSObtenerArticulo(string fechaInicial, string fechaFinal, string valReporte) {
            object[] results = this.Invoke("WSObtenerArticulo", new object[] {
                        fechaInicial,
                        fechaFinal,
                        valReporte});
            return ((Reporte[])(results[0]));
        }
        
        /// <remarks/>
        public void WSObtenerArticuloAsync(string fechaInicial, string fechaFinal, string valReporte) {
            this.WSObtenerArticuloAsync(fechaInicial, fechaFinal, valReporte, null);
        }
        
        /// <remarks/>
        public void WSObtenerArticuloAsync(string fechaInicial, string fechaFinal, string valReporte, object userState) {
            if ((this.WSObtenerArticuloOperationCompleted == null)) {
                this.WSObtenerArticuloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSObtenerArticuloOperationCompleted);
            }
            this.InvokeAsync("WSObtenerArticulo", new object[] {
                        fechaInicial,
                        fechaFinal,
                        valReporte}, this.WSObtenerArticuloOperationCompleted, userState);
        }
        
        private void OnWSObtenerArticuloOperationCompleted(object arg) {
            if ((this.WSObtenerArticuloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSObtenerArticuloCompleted(this, new WSObtenerArticuloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Articulos {
        
        private int idarticuloField;
        
        private string nombreArticuloField;
        
        private string autorField;
        
        private string contenidoField;
        
        private int idEstatusArticuloField;
        
        private string versionField;
        
        private string fechaCreacionField;
        
        private string nombreCategoriaField;
        
        /// <remarks/>
        public int idarticulo {
            get {
                return this.idarticuloField;
            }
            set {
                this.idarticuloField = value;
            }
        }
        
        /// <remarks/>
        public string nombreArticulo {
            get {
                return this.nombreArticuloField;
            }
            set {
                this.nombreArticuloField = value;
            }
        }
        
        /// <remarks/>
        public string autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
            }
        }
        
        /// <remarks/>
        public string contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
            }
        }
        
        /// <remarks/>
        public int idEstatusArticulo {
            get {
                return this.idEstatusArticuloField;
            }
            set {
                this.idEstatusArticuloField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string nombreCategoria {
            get {
                return this.nombreCategoriaField;
            }
            set {
                this.nombreCategoriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reporte {
        
        private int idArticuloField;
        
        private string nombreArticuloField;
        
        private string categoriaField;
        
        private int visitasField;
        
        private string palabraBuscadaField;
        
        private int numeroDeBusquedasField;
        
        private int promedioCalificacionField;
        
        private int calificacionTotalField;
        
        private int categoriaMasVistaField;
        
        /// <remarks/>
        public int idArticulo {
            get {
                return this.idArticuloField;
            }
            set {
                this.idArticuloField = value;
            }
        }
        
        /// <remarks/>
        public string nombreArticulo {
            get {
                return this.nombreArticuloField;
            }
            set {
                this.nombreArticuloField = value;
            }
        }
        
        /// <remarks/>
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        public int visitas {
            get {
                return this.visitasField;
            }
            set {
                this.visitasField = value;
            }
        }
        
        /// <remarks/>
        public string palabraBuscada {
            get {
                return this.palabraBuscadaField;
            }
            set {
                this.palabraBuscadaField = value;
            }
        }
        
        /// <remarks/>
        public int numeroDeBusquedas {
            get {
                return this.numeroDeBusquedasField;
            }
            set {
                this.numeroDeBusquedasField = value;
            }
        }
        
        /// <remarks/>
        public int promedioCalificacion {
            get {
                return this.promedioCalificacionField;
            }
            set {
                this.promedioCalificacionField = value;
            }
        }
        
        /// <remarks/>
        public int calificacionTotal {
            get {
                return this.calificacionTotalField;
            }
            set {
                this.calificacionTotalField = value;
            }
        }
        
        /// <remarks/>
        public int categoriaMasVista {
            get {
                return this.categoriaMasVistaField;
            }
            set {
                this.categoriaMasVistaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BusquedaTitulo {
        
        private int idarticuloField;
        
        private string nombreArticuloField;
        
        /// <remarks/>
        public int idarticulo {
            get {
                return this.idarticuloField;
            }
            set {
                this.idarticuloField = value;
            }
        }
        
        /// <remarks/>
        public string nombreArticulo {
            get {
                return this.nombreArticuloField;
            }
            set {
                this.nombreArticuloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CategoriasxSubcategorias {
        
        private int idCategoriasField;
        
        private int idPadreField;
        
        private int idHijoField;
        
        private string nombreCategoriaField;
        
        private string descripcionCategoriaField;
        
        private int estatusField;
        
        /// <remarks/>
        public int idCategorias {
            get {
                return this.idCategoriasField;
            }
            set {
                this.idCategoriasField = value;
            }
        }
        
        /// <remarks/>
        public int idPadre {
            get {
                return this.idPadreField;
            }
            set {
                this.idPadreField = value;
            }
        }
        
        /// <remarks/>
        public int idHijo {
            get {
                return this.idHijoField;
            }
            set {
                this.idHijoField = value;
            }
        }
        
        /// <remarks/>
        public string nombreCategoria {
            get {
                return this.nombreCategoriaField;
            }
            set {
                this.nombreCategoriaField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionCategoria {
            get {
                return this.descripcionCategoriaField;
            }
            set {
                this.descripcionCategoriaField = value;
            }
        }
        
        /// <remarks/>
        public int estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSOptenerArtCompletedEventHandler(object sender, WSOptenerArtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSOptenerArtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSOptenerArtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Articulos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Articulos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSOptenerCatgCompletedEventHandler(object sender, WSOptenerCatgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSOptenerCatgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSOptenerCatgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoriasxSubcategorias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoriasxSubcategorias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSBusquedaTituloCompletedEventHandler(object sender, WSBusquedaTituloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSBusquedaTituloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSBusquedaTituloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BusquedaTitulo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BusquedaTitulo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSConsultarArticuloxIdCompletedEventHandler(object sender, WSConsultarArticuloxIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSConsultarArticuloxIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSConsultarArticuloxIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Articulos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Articulos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSBusquedaArticulosxClickCompletedEventHandler(object sender, WSBusquedaArticulosxClickCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSBusquedaArticulosxClickCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSBusquedaArticulosxClickCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Articulos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Articulos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSGuardarPalabraBuscadaCompletedEventHandler(object sender, WSGuardarPalabraBuscadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGuardarPalabraBuscadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGuardarPalabraBuscadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSOpregistrarArtCompletedEventHandler(object sender, WSOpregistrarArtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSOpregistrarArtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSOpregistrarArtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSOpconsultarArtxValidarCompletedEventHandler(object sender, WSOpconsultarArtxValidarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSOpconsultarArtxValidarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSOpconsultarArtxValidarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSConsultarArtEdicionCompletedEventHandler(object sender, WSConsultarArtEdicionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSConsultarArtEdicionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSConsultarArtEdicionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSConsultarCategoriasCompletedEventHandler(object sender, WSConsultarCategoriasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSConsultarCategoriasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSConsultarCategoriasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSEditarArtCompletedEventHandler(object sender, WSEditarArtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSEditarArtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSEditarArtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSConsultarArtPorValidarCompletedEventHandler(object sender, WSConsultarArtPorValidarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSConsultarArtPorValidarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSConsultarArtPorValidarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSOguardarEstatusArticuloAprobarCompletedEventHandler(object sender, WSOguardarEstatusArticuloAprobarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSOguardarEstatusArticuloAprobarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSOguardarEstatusArticuloAprobarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSConsultarGruposxUsuarioCompletedEventHandler(object sender, WSConsultarGruposxUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSConsultarGruposxUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSConsultarGruposxUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSconsultarCategoriasCompletedEventHandler(object sender, WSconsultarCategoriasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSconsultarCategoriasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSconsultarCategoriasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoriasxSubcategorias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoriasxSubcategorias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSgetSinHijosCompletedEventHandler(object sender, WSgetSinHijosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSgetSinHijosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSgetSinHijosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoriasxSubcategorias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoriasxSubcategorias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSgetSinPadresCompletedEventHandler(object sender, WSgetSinPadresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSgetSinPadresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSgetSinPadresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoriasxSubcategorias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoriasxSubcategorias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSgetSizeCompletedEventHandler(object sender, WSgetSizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSgetSizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSgetSizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoriasxSubcategorias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoriasxSubcategorias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSgetListCompletedEventHandler(object sender, WSgetListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSgetListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSgetListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoriasxSubcategorias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoriasxSubcategorias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSguardarCategoriasCompletedEventHandler(object sender, WSguardarCategoriasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSguardarCategoriasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSguardarCategoriasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSguardarCategoriasEditCompletedEventHandler(object sender, WSguardarCategoriasEditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSguardarCategoriasEditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSguardarCategoriasEditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSguardarRelacionCompletedEventHandler(object sender, WSguardarRelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSguardarRelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSguardarRelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSeliminarCategoriasCompletedEventHandler(object sender, WSeliminarCategoriasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSeliminarCategoriasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSeliminarCategoriasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WSObtenerArticuloCompletedEventHandler(object sender, WSObtenerArticuloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSObtenerArticuloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSObtenerArticuloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reporte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reporte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591