//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBSupportCenter.WSsupport1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSsupportCenterClassSoap", Namespace="http://tempuri.org/")]
    public partial class WSsupportCenterClass : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback dataMenuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSsupportCenterClass() {
            this.Url = global::WBSupportCenter.Properties.Settings.Default.WBSupportCenter_WSsupport1_WSsupportCenterClass;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event dataMenuCompletedEventHandler dataMenuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dataMenu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioEntidades[] dataMenu(int idrol) {
            object[] results = this.Invoke("dataMenu", new object[] {
                        idrol});
            return ((UsuarioEntidades[])(results[0]));
        }
        
        /// <remarks/>
        public void dataMenuAsync(int idrol) {
            this.dataMenuAsync(idrol, null);
        }
        
        /// <remarks/>
        public void dataMenuAsync(int idrol, object userState) {
            if ((this.dataMenuOperationCompleted == null)) {
                this.dataMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OndataMenuOperationCompleted);
            }
            this.InvokeAsync("dataMenu", new object[] {
                        idrol}, this.dataMenuOperationCompleted, userState);
        }
        
        private void OndataMenuOperationCompleted(object arg) {
            if ((this.dataMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataMenuCompleted(this, new dataMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioEntidades {
        
        private string nombreField;
        
        private string apPaternoField;
        
        private string apMaternoField;
        
        private string rFCField;
        
        private string idPuestoField;
        
        private string c_CPField;
        
        private string idEstadoField;
        
        private string emailField;
        
        private string fecha_altaField;
        
        private string fecha_modField;
        
        private string acceso_a_sistemasField;
        
        private string estatusField;
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string apPaterno {
            get {
                return this.apPaternoField;
            }
            set {
                this.apPaternoField = value;
            }
        }
        
        /// <comentarios/>
        public string apMaterno {
            get {
                return this.apMaternoField;
            }
            set {
                this.apMaternoField = value;
            }
        }
        
        /// <comentarios/>
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <comentarios/>
        public string idPuesto {
            get {
                return this.idPuestoField;
            }
            set {
                this.idPuestoField = value;
            }
        }
        
        /// <comentarios/>
        public string c_CP {
            get {
                return this.c_CPField;
            }
            set {
                this.c_CPField = value;
            }
        }
        
        /// <comentarios/>
        public string idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
            }
        }
        
        /// <comentarios/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_alta {
            get {
                return this.fecha_altaField;
            }
            set {
                this.fecha_altaField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_mod {
            get {
                return this.fecha_modField;
            }
            set {
                this.fecha_modField = value;
            }
        }
        
        /// <comentarios/>
        public string acceso_a_sistemas {
            get {
                return this.acceso_a_sistemasField;
            }
            set {
                this.acceso_a_sistemasField = value;
            }
        }
        
        /// <comentarios/>
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void dataMenuCompletedEventHandler(object sender, dataMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioEntidades[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioEntidades[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591